version: "3.8"

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      # Add other environment variables as needed
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    # Use stdin_open and tty for better terminal interaction
    stdin_open: true
    tty: true

  # Example database service for development
  # db:
  #   image: postgres:14-alpine
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=webby_dev
  #   volumes:
  #     - postgres_dev_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped
# Uncomment to enable volumes
# volumes:
#   postgres_dev_data:
