version: "3.8"

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Add other environment variables as needed
      # - DATABASE_URL=your-database-url
      # - API_KEY=your-api-key
    restart: always
    healthcheck:
      test:
        ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    # Uncomment to enable volumes for persistent storage
    # volumes:
    #   - ./logs:/app/logs

  # Example database service - uncomment and configure as needed
  # db:
  #   image: postgres:14-alpine
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=webby
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
# Uncomment to enable volumes
# volumes:
#   postgres_data:
